*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 20 23:52:03 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
writing pidfile to /home/maoss/django/workplace/Blog/script/uwsgi.pid
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog/
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
bind(): Cannot assign requested address [core/socket.c line 769]
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 20 23:52:45 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
writing pidfile to /home/maoss/django/workplace/Blog/script/uwsgi.pid
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog/
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:8080 fd 3
uwsgi socket 0 bound to UNIX address /home/maoss/django/workplace/Blog/uwsgi.sock fd 6
Python version: 2.7.12 (default, Nov 20 2017, 18:23:56)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x14eb5f0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 485712 bytes (474 KB) for 5 cores
*** Operational MODE: preforking ***
ImportError: No module named teacher.wsgi
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6739)
spawned uWSGI worker 1 (pid: 6740, cores: 1)
spawned uWSGI worker 2 (pid: 6741, cores: 1)
spawned uWSGI worker 3 (pid: 6742, cores: 1)
spawned uWSGI worker 4 (pid: 6743, cores: 1)
spawned uWSGI worker 5 (pid: 6744, cores: 1)
spawned uWSGI http 1 (pid: 6745)
--- no python application found, check your startup logs for errors ---
[pid: 6743|app: -1|req: -1/1] 127.0.0.1 () {38 vars in 683 bytes} [Sat Jan 20 23:53:00 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 20 23:53:43 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
writing pidfile to /home/maoss/django/workplace/Blog/script/uwsgi.pid
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog/
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8080).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 6740|app: -1|req: -1/2] 127.0.0.1 () {38 vars in 683 bytes} [Sat Jan 20 23:53:45 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6741|app: -1|req: -1/3] 127.0.0.1 () {38 vars in 684 bytes} [Sat Jan 20 23:53:47 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 20 23:55:40 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
writing pidfile to /home/maoss/django/workplace/Blog/script/uwsgi.pid
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog/
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8080).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 6742|app: -1|req: -1/4] 127.0.0.1 () {38 vars in 684 bytes} [Sat Jan 20 23:55:43 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6744|app: -1|req: -1/5] 127.0.0.1 () {38 vars in 684 bytes} [Sat Jan 20 23:55:44 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 20 23:57:31 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8080).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 6743|app: -1|req: -1/6] 127.0.0.1 () {38 vars in 684 bytes} [Sat Jan 20 23:57:33 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 20 23:59:23 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8080).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 6740|app: -1|req: -1/7] 127.0.0.1 () {38 vars in 684 bytes} [Sat Jan 20 23:59:26 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6741|app: -1|req: -1/8] 127.0.0.1 () {38 vars in 684 bytes} [Sat Jan 20 23:59:27 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sun Jan 21 00:04:24 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog/CluasBlog
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8080).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 6742|app: -1|req: -1/9] 127.0.0.1 () {38 vars in 684 bytes} [Sun Jan 21 00:04:26 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6744|app: -1|req: -1/10] 127.0.0.1 () {38 vars in 684 bytes} [Sun Jan 21 00:04:39 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 6743|app: -1|req: -1/11] 127.0.0.1 () {38 vars in 684 bytes} [Sun Jan 21 00:04:45 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sun Jan 21 00:05:54 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8080).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 6740|app: -1|req: -1/12] 127.0.0.1 () {38 vars in 684 bytes} [Sun Jan 21 00:05:56 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
gateway "uWSGI http 1" has been buried (pid: 6745)
...brutally killing workers...
[deadlock-detector] a process holding a robust mutex died. recovering...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/maoss/django/workplace/Blog
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 6 mapped to socket 0 (/home/maoss/django/workplace/Blog/uwsgi.sock)
running /home/maoss/django/venv_Blog/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /static => /home/maoss/django/workplace/Blog/blog/static
*** Starting uWSGI 2.0.15 (64bit) on [Sun Jan 21 00:08:05 2018] ***
compiled with version: 5.4.0 20160609 on 20 January 2018 19:43:41
os: Linux-4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/maoss/django/workplace/Blog
detected binary path: /home/maoss/django/venv_Blog/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/maoss/django/workplace/Blog
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
Python version: 2.7.12 (default, Nov 20 2017, 18:23:56)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f0ea50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72760 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1f0ea50 pid: 6739 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6739, cores: 1)
